deployments:
- actions:
  - command: kubeadm reset -f
    commandSudo: root
    name: Reset Kubernetes
    type: command
  - command: dpkg -r kubeadm kubelet kubectl cri-tools kubernetes-cni
    commandSudo: root
    name: Remove packages
    type: command
  - command: rm -rf /opt/cni/bin
    commandSudo: root
    name: Remove any remaining cni directories 
    type: command
  hosts:
  - 192.168.1.101
  name: Reset any Kubernetes configuration (and remove packages)
  parallel: false
- actions:
  - destination: /tmp/ubuntu.tar.gz
    name: Upload Ubuntu Packages
    source: ./ubuntu.tar.gz
    type: upload
  - command: tar -C /tmp -xvzf /tmp/ubuntu.tar.gz
    name: Extract Ubuntu packages
    type: command
  - command: dpkg -i /tmp/ubuntu/*
    commandSudo: root
    name: Install Ubuntu packages
    type: command
  - destination: /tmp/docker.tar.gz
    name: Upload Docker Packages
    source: ./docker.tar.gz
    type: upload
  - command: tar -C /tmp -xvzf /tmp/docker.tar.gz
    name: Extract Docker packages
    type: command
  - command: dpkg -i /tmp/docker/*
    commandSudo: root
    name: Install Docker packages
    type: command
  - destination: /tmp/kubernetes.tar.gz
    name: Upload Kubernetes Packages
    source: ./kubernetes.tar.gz
    type: upload
  - command: tar -C /tmp -xvzf /tmp/kubernetes.tar.gz
    name: Extract Kubernetes packages
    type: command
  - command: dpkg -i /tmp/kubernetes/*
    commandSudo: root
    name: Install Kubernetes packages
    type: command
  - command: rm -rf /tmp/kubernetes /tmp/docker /tmp/ubuntu
    commandSudo: root
    name: Tidy installation directories
    type: command
  hosts:
  - 192.168.1.101
  name: Configure host OS for kubernetes nodes
  parallel: false
- actions:
  - name: Push kubernetes images for workers
    plugin:
      imageName:
      - k8s.gcr.io/pause:3.1
      - k8s.gcr.io/coredns:1.3.1
      - k8s.gcr.io/kube-proxy:v1.14.0
      localSudo: true
      remoteSudo: true
    type: docker/image
  - name: Push kubernetes images for managers
    plugin:
      imageName:
      - k8s.gcr.io/kube-apiserver:v1.14.0
      - k8s.gcr.io/kube-controller-manager:v1.14.0
      - k8s.gcr.io/kube-scheduler:v1.14.0
      localSudo: true
      remoteSudo: true
    type: docker/image
  - name: Push etcd image
    plugin:
      imageName:
      -  k8s.gcr.io/etcd:3.3.10
      localSudo: true
      remoteSudo: true
    type: docker/image
  hosts:
  - 192.168.1.101
  name: Deploy Kubernetes Images for 1.14.0
  parallel: false
- actions:
  - command: kubeadm init --kubernetes-version "v1.14.0" --pod-network-cidr=172.16.0.0/16
    commandSudo: root
    name: Initialise Cluster
    type: command
  - command: rm -rf ~/.kube ; mkdir -p ~/.kube ; sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config ; sudo chown $(id -u):$(id -g) $HOME/.kube/config
    name: Allow access to control plane
    type: command
    commandSudo: root
  hosts:
  - 192.168.1.101
  name: Initialise Kubernetes Master (1.14)
  parallel: false
- actions:
  - name: Push calico images for workers
    plugin:
      imageName:
      - calico/node:v3.6.1
      - calico/cni:v3.6.1
      localSudo: true
      remoteSudo: true
    type: docker/image
  - name: Push calico kube-controllers image
    plugin:
      imageName:
      - calico/kube-controllers:v3.6.1
      localSudo: true
      remoteSudo: true
    type: docker/image
  - command: kubectl apply -f -
    commandPipeCmd: curl https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml | sed "s?192.168.0.0/16?172.16.0.0/16?g"
    name: Import Calico manifset
    type: command
  hosts:
  - 192.168.1.101
  name: Deploy Calico (3.6)
  parallel: false